### PR TITLE
Tests for operators

### LINKED ISSUE #31: Test if every operator has a role
As discussed in #29 , a test to check whether our `map[operator]role` is missing any operators.
One approach could be:

1. use `reflect` or  `golang.org/x/tools/go/packages` to go through `header.go`, finding all constants of type `Operator`
2. for each const we find, check if `Operator.Role()` returns an error
3. if we have no errors, we know that each of our operators has a role assigned

@redraskal do you think we should also add a test that queries the Ubisoft page to check if we are missing any operators in `header.go` that are present in the game?

### PR DESCRIPTION
**Pull request by stnokott**
Adds two tests:

- validate that every operator constant in `header.go` has a role by checking if the `Role` function is erroneous
- validate that every operator on the official Ubisoft operator page (https://www.ubisoft.com/de-de/game/rainbow-six/siege/game-info/operators) is also present in our `header.go`

When both of these succeed, we can be pretty certain that our data is complete.
The only uncertainty will be if the IDs in `header.go` match the replay files.

Closes #31 

---

@redraskal 
Let me know what you think about the added comment in `genops.go`:
> 	// since we have a test validating that every operator has a role,
	// it could be argued that this method does not need to return an error
	// and instead could just panic if the role isnt found

### CODE REVIEW

**Comment by stnokott** [comment]
Tests are failing due to #33

**Comment by redraskal** [comment]
I think panic is ok in that case

**Review by redraskal — APPROVED** [review]

**Comment by stnokott** [comment]
> I think panic is ok in that case

I'll change that tomorrow, don't have any more time today.
Or just merge this now and I'll open a new PR for that change, whatever you prefer.

**Comment by redraskal** [comment]
> > I think panic is ok in that case
> 
> I'll change that tomorrow, don't have any more time today. Or just merge this now and I'll open a new PR for that change, whatever you prefer.

I'll just merge and make a release so everyone has functional Year 8 binaries

**Pull request merged**
